project:
  type: website
  resources:
    - CNAME
    - "/newsletter/**"
    - .well-known/atproto-did

website:
  title: "IBS-AR"
  favicon: favicon.ico
  repo-url: https://github.com/IBS-AR/IBS-AR.github.io
  repo-actions: [edit, issue]
  sidebar:
    logo: logo.svg
  navbar:
    logo: logo.svg
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - council.qmd
      - news.qmd
      - text: Scholarships and Prizes
        menu:
          - href: scholarships.qmd
            text: Scholarships
          - href: awards.qmd
            text: Prizes and awards
          - href: alfaward.qmd
            text: Alf Cornish award
      - conferences.qmd
      - membership.qmd
      - contact.qmd
    tools:
      - icon: github
        url: https://github.com/IBS-AR/IBS-AR.github.io



format:
  html:
    theme: [flatly, ibs-theme.scss]
    css: styles.css
    toc: true



