---
title: "About us"
---

## Purpose


The International Biometric Society (IBS) is devoted to the development and application of statistical and mathematical theory and methods in the Biosciences, including agriculture, biomedical science and public health, ecology, environmental sciences, forestry, and allied disciplines. It welcomes as members statisticians, mathematicians, biological scientists, and others devoted to interdisciplinary efforts in advancing the collection and interpretation of information in the biosciences.

The Society publishes two journals, [Biometrics](https://www.biometricsociety.org/publications/biometrics), reporting communications consistent with the Society's mission, and, jointly with the American Statistical Association, the Journal of Agricultural, Biological, and Environmental Statistics ([JABES](https://www.biometricsociety.org/publications/jabes)).

The IBS is organised into geographically-defined regions, each with at least 50 members. The Australasian Region (IBS-AR) is one of over 30 regions under the IBS umbrella. It provides to over [200 members of the International Biometric Society](membership.html) who reside in Australia, New Zealand and nearby countries a local focus and support for biometrics undertaken in this region.

## Definition of Biometrics

The terms "Biometrics" and "Biometry" have been used since early in the 20th century to refer to the field of development of statistical and mathematical methods applicable to data analysis problems in the biological sciences.

Statistical methods for the analysis of data from agricultural field experiments to compare the yields of different varieties of wheat, for the analysis of data from human clinical trials evaluating the relative effectiveness of competing therapies for disease, or for the analysis of data from environmental studies on the effects of air or water pollution on the appearance of human disease in a region or country are all examples of problems that would fall under the umbrella of "Biometrics" as the term has been historically used.

The journal "Biometrics" is a scholarly publication sponsored by a non-profit professional society (the International Biometric Society) devoted to the dissemination of accounts of the development of such methods and their application in real scientific contexts.

Recently, the term "Biometrics" has also been used to refer to the emerging field of technology devoted to identification of individuals using biological traits, such as those based on retinal or iris scanning, fingerprints, or face recognition. Neither the journal "Biometrics" nor the International Biometric Society is engaged in research, marketing, or reporting related to this technology. Likewise, the editors and staff of the journal are not knowledgeable in this area.

## Rules of Incorporation of IBS-AR as an Association

The [rules](docs/INTERNATIONAL BIOMETRIC SOCIETY AUSTRALASIAN REGION INC A06212 - Rules 22 December 2020.pdf) for the Australasian Region date from December 2020 when incorporation occurred.

## Code of Conduct

Our regional [code of conduct](docs/IBS-AR-Code-of-Conduct.pdf) was developed in 2019.

## History

Please refer to [Biometric Bulletin Vol 17 No 3](docs/BiometricBulletin2000Vol17(3)pp14-15.pdf) (July-September 2000) by Sue Wilson for details.

## Elections


The President serves a two year term. A President-elect is chosen by ballot at the Annual General Meeting (AGM) falling in the middle of the term of the current President and serves as Vice-President from then to the end of the next AGM, whence they become President. At the same time the immediate past president become Vice-President for one year. The officers and members of the Council, other than President and ex-officio members, are chosen by a ballot of Members prior to each AGM.


