---
title: "E.A. (Alf) Cornish award"
---

## Background

As reported in the [February 2012 IBS-AR newsletter](newsletter/IBS-AR-Newsletter-Feb-2012.pdf), the Australasian Region of the International Biometric Society created the 'ALF' award, named after E.A. (Alf) Cornish who was the first (vice-) president of the Australasian Region, from 1948-1950, and IBS President during 1956-1957. More information about Alf’s career is [here](https://www.asap.unimelb.edu.au/bsparcs/aasmemoirs/cornish.htm).

The award is for recognition of a current member in the Australasian Region who has given ‘longtime’ service to the Biometric Society and to the advancement of biometry. The nominated member should have been a member for the minimum of the last 5 years.

Members are invited to submit an application to the Secretary with the nomination of a member who may be eligible to be considered. The closing date for nominations is three months before the starting date of our biennial conferences, typically about the end of August.

## Previous winners

Awardees | Regional conference |
---------|---------------------|
Arthur R Gilmour  | Kiama, NSW, Dec 7, 2011
Susan R Wilson    | Kiama, NSW, Dec 7, 2011
Ian R James       | Mandurah, WA, Dec 4, 2013
Jeffrey T Wood    | Mandurah, WA, Dec 4, 2013
Kaye E Basford    | Hobart, Tasmania, Dec 2, 2015
Brian R Cullis    | Hobart, Tasmania, Dec 2, 2015
Warren Muller     | Kingscliff, NSW, Nov 29, 2017
Alan Welsh        | Kingscliff, NSW, Nov 29, 2017
Emlyn Williams    | Adelaide, SA, Dec 5, 2019
David Baird	      | Adelaide, SA, Dec 5, 2019
Mario D'Antuono   | Bay of Islands, NZ, Nov 30, 2023
Chris Triggs      | Bay of Islands, NZ, Nov 30, 2023

