---
title: Conferences
---

2023 International Biometric Society Australasian Region conference

Our main activity is our regional biennial conference, but the planned 2021 conference in the Bay of Islands was postponed, initially to 2022, but is now happening in 2023! The direct link is biometricsboi.nz.

The dates are 27 November to 1 December 2023, to be held at the Copthorne Hotel and Resort Bay of Islands, Waitangi, NZ. As was intended for 2021, the 2023 conference aims to be a joint event with Statistical Ecology and Environmental Monitoring (SEEM) conference. Conference themes for 2023 are:

Statistical Genetics/’Omics
Spatial/Temporal Modelling
Design/Surveys
Biostatistics
Agricultural Statistics
Demographic/Population Modelling
Multivariate Statistics
Statistical Consulting—Best Practice & Collaboration
Data Governance/Sovereignty
Machine Learning for Environmental and Ecological Applications
A biennial meeting is one of the main activities of the region, which enables members and non-members to come together to exchange ideas, learn about new research methodologies and applications, network and establish important contacts and collaboration opportunities. These five-day conferences are renowned for being intimate regarding numbers of participants, yet large enough to facilitate worthwhile invited and contributed talks as well as poster presentations. The program typically has a reception gathering, a poster event, an excursion afternoon and an evening conference dinner, all to encourage social and professional networking. Specialist pre-conference short-courses on the first day are also a feature for those interested or wanting professional development.

You can read more about conferences here.
