---
title: Regional Council
---

The Australasian Region is governed by a council comprising the President, Vice-President, Secretary, Treasurer, Membership Officer, Social Media Coordinator and Public Officer of the region, as well as the website manager, regional newsletter correspondent, and regional representatives to IBS. We currently have one member on the IBS Executive Board and three on Council, as seen below.

A President-elect shall be chosen by ballot at the Annual General Meeting (AGM) falling in the middle of the term of the current President. The President-Elect shall assume the office of Vice-President at the end of the AGM at which they are elected, and the office of President at the end of the next AGM, when the outgoing President becomes Vice-President as the immediate Past-President. That is, the Vice-President alternates between Past-President and President-Elect each year.

Nominations for each vacant position are called for by the Secretary towards the end of the calendar year. If more than one nomination is received for a particular position, then members are required to vote for a preferred candidate for the position at the annual general meeting (AGM). Otherwise, no formal election is necessary.

The regional council currently comprises the following people:

